#
# mmc - mattmc3's starship config
#

# A minimal left prompt
format = """\
$shell\
$python\
$directory\
$git_branch${custom.git_status_dirty}$git_status\
$line_break\
$character\
"""

# Move the rest of the prompt to the right
right_format = """$status$cmd_duration"""

# Timeout for commands executed by starship (in milliseconds)
command_timeout = 2000

# Set the color palette
palette = "wombat"

# Define custom colors
[palettes.tokyo_night]
black = '#15161e'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
purple = '#bb9af7'
red = '#f7768e'
white = '#a9b1d6'
yellow = '#e0af68'
pink = '#ff6ac1'

[palettes.wombat]
black = '#000000'
blue = '#5da9f6'
cyan = '#82fff7'
green = '#b1e969'
purple = '#e86aff'
red = '#ff615a'
white = '#dedacf'
yellow = '#ebd99c'

[character]
format = "$symbol "
success_symbol = "[â±](purple)"
error_symbol = "[â±](red)"
vimcmd_symbol = "[â°](cyan)"

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'white'

[directory]
style = "blue"
truncation_length = 0
truncate_to_repo = false
truncation_symbol = ""

[username]
format = "[$user]($style) "

# Right-side prompt items use left space padding
[git_branch]
format = '[$branch]($style)'
style = 'green'

[git_status]
format = "[( $ahead_behind$stashed)]($style)"
style = "cyan"
stashed = "â‰¡"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
# other symbols â€¢ * ï¹¡ ï¼Š âœ±
symbol = "â€¢"
style = "yellow"
format = "[$symbol]($style)"
shell = ["sh"]

[shell]
# other fishes ó°ˆº ğŸŸ ğŸ 
fish_indicator = 'ğŸŸ'
powershell_indicator = 'ï‘ _'
pwsh_indicator = 'ï‘ _'
zsh_indicator = 'ó €¥%'
style = 'cyan bold'
disabled = false

[cmd_duration]
format = '[$duration ]($style)'

[status]
disabled = false
pipestatus = true
format = '[($symbol$int )]($style)'
symbol = 'âœ˜'
pipestatus_format = '\[$pipestatus\]($style)'
