add_newline = false

# A minimal left prompt
format = """$python$directory$character"""

# move the rest of the prompt to the right
right_format = """$status$git_branch$git_status"""

[character]
success_symbol = "[❯](purple)[❯](cyan)"
error_symbol = "[❯](yellow)[❯](red)"
vicmd_symbol = "[❮](purple)[❮](cyan)"
# success_symbol = "[⨠](purple)"
# error_symbol = "[⨠](red)"
# vicmd_symbol = "[⪻](yellow)"

[python]
format = '\($virtualenv\) '

[directory]
style = "blue"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = ' [$branch]($style)'
style = 'bold green'

[git_status]
format = '$all_status$ahead_behind'
ahead = ' [⬆](bold purple)'
behind = ' [⬇](bold purple)'
staged = ' [✚](green)'
deleted = ' [✖](red)'
renamed = ' [➜](purple)'
stashed = ' [✭](cyan)'
untracked = ' [◼](white)'
modified = ' [✱](blue)'
conflicted = ' [═](yellow)'
diverged = ' ⇕'
up_to_date = ''

[cmd_duration]
format = ' [$duration]($style)'

[line_break]
disabled = true

[status]
disabled = false
symbol = ' ✘'
